### ISSUE TITLE
Help. sensor not loading

### ISSUE THREAD

**Issue by AndreySupr** [shammysha/homeassistant-binance-pool#24]
Logger: homeassistant.setup
Source: custom_components/binance_pool/__init__.py:342
Integration: binance_pool ([documentation](https://github.com/shammysha/homeassistant-binance-pool), [issues](https://github.com/shammysha/homeassistant-binance-pool/issues))
First occurred: 12:07:03 (1 occurrences)
Last logged: 12:07:03

Error during setup of component binance_pool
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/binance_pool/__init__.py", line 77, in async_setup
    await binance_data.async_update();
  File "/config/custom_components/binance_pool/__init__.py", line 246, in async_update
    balances = await self.client.async_get_capital_balances()
  File "/config/custom_components/binance_pool/__init__.py", line 413, in async_get_capital_balances
    return await self.async_request_capital_api('get', 'config/getall', True, data=params)
  File "/config/custom_components/binance_pool/__init__.py", line 342, in async_request_capital_api
    return await self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 6472, in _request
    async with getattr(self.session, method)(uri, **kwargs) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.binance.com:443 ssl:default [Try again]

**Comment by shammysha** [comment]
Hello.

>> Cannot connect to host api.binance.com:443

Please, check result of commands 
`ping api.binance.com` or
`telnet api.binance.com:443` from same subnet, as HA's server

**Comment by AndreySupr** [comment]
64 bytes from server-108-157-213-230.arn56.r.cloudfront.net (108.157.213.230): icmp_seq=22 ttl=63 time=110 ms
64 bytes from server-108-157-213-230.arn56.r.cloudfront.net (108.157.213.230): icmp_seq=23 ttl=63 time=113 ms
64 bytes from server-108-157-213-230.arn56.r.cloudfront.net (108.157.213.230): icmp_seq=24 ttl=63 time=119 ms
icmp_seq=16 ttl=63 time=139 ms
64 bytes from server-108-157-213-230.arn56.r.cloudfront.net (108.157.213.230): icmp_seq=17 ttl=63 time=128 ms

How interesting it works. I don't understand. problem after power off. apparently while the router is loading - the integration gives an error. and itself does not connect to the binance server. reboot doesn't help. only if you disconnect the raspberry pi from the network. and then two times. Setup of binance_pool is taking longer than 300 seconds. Startup will proceed without waiting any longer
now this is an error. but all the sensors appeared. why is it necessary to turn off/on the raspberry constantly? how can you fix this?

**Comment by amgstone** [comment]
Logger: custom_components.binance_pool
Source: custom_components/binance_pool/__init__.py:86
Integration: Binance Pool ([documentation](https://github.com/shammysha/homeassistant-binance-pool), [issues](https://github.com/shammysha/homeassistant-binance-pool/issues))
First occurred: 21:37:51 (1 occurrences)
Last logged: 21:37:51

Error fetching data from binance.com: TimeoutError()

**Comment by shammysha** [comment]
Hello, 
Please, check Your network connection to api.binance.com
This error does not a component probem...

**Comment by amgstone** [comment]
test ok

**Comment by shammysha** [comment]
https://github.com/shammysha/homeassistant-binance-pool/releases/tag/v1.5.12
